version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    image: andrewuni3/library-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 59CVZbNKy3fB41B8&o$C8P
    depends_on:
      - mysql

  frontend:
    image: andrewuni3/library-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
